name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -V
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # outils dev
          pip install flake8 nose coverage

      - name: Set PYTHONPATH (src)
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE/src" >> $GITHUB_ENV

      - name: Lint (Flake8)
        run: |
          flake8 src test

      - name: Tests (nose) + JUnit + coverage XML
        run: |
          mkdir -p test-reports
          coverage run -m nose -v --with-xunit --xunit-file=test-reports/nosetests.xml
          coverage xml -o test-reports/coverage.xml

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: test-reports
          if-no-files-found: error